version: '3'

services:
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
        - "8000:80"
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=${MYSQL_HOST}
    restart: unless-stopped
    depends_on:
        - db
    networks:
      - app-network
  db:
    image: mariadb:${MYSQL_VERSION}
    container_name: ${MYSQL_HOST}
    restart: unless-stopped
    env_file:
        - ".env"
    environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
        - "./data/db/mysql:/var/lib/mysql"
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network
    
  php-fpm:
    image: nanoninja/php-fpm:${PHP_VERSION}
    volumes:
            - "./etc/php:/usr/local/etc/php/conf.d/php.ini"
            - "./data/web:/var/www/html"
            - "./data/log/php-fpm:/var/log/php-fpm"
    restart: unless-stopped
    env_file: .env
    # environment:
    #   - WORDPRESS_DB_HOST=db:3306
    #   - WORDPRESS_DB_USER=$MYSQL_USER
    #   - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
    #   - WORDPRESS_DB_NAME=wordpress
    networks:
      - app-network

  webserver:
    # depends_on:
    #   - php-fpm
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./data/web:/var/www/html
      - ./etc/nginx:/etc/nginx/conf.d
      - ./etc/ssl:/etc/letsencrypt
      - ./data/log/nginx:/var/log/nginx
    networks:
      - app-network

  # certbot:
  #   depends_on:
  #     - webserver
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./etc/ssl:/etc/letsencrypt
  #     - ./data/web:/var/www/html
  #   command: certonly --webroot --webroot-path=/var/www/html --email sammy@example.com --agree-tos --no-eff-email --force-renewal -d example.com -d www.example.com

networks:
  app-network:
    driver: bridge